### ISSUE TITLE
some questions about viewing picture's detail

### ISSUE THREAD

**Issue by dingyinghu** [yellowbluesky/PixivforMuzei3#67] opened 2020-02-04 04:41 UTC
In the Pixiv for Muzei Plus source, i can call the browser or Pixiv app to open the original link by clicking the picture name. Of crouse, it can work in the default source, but it can't work in this source.Sometimes,It will respond to my click and pop up the call interface, but it will not open the app，whatever browser or Pixiv app

**Comment by yellowbluesky** [comment] 2020-02-04 05:36
Hi,

What version of Android are you running, and what Android skin do you have (MIUI, EMUI, OneUI, ColorOS, etc)?

Can you tell me what update modes you have tried, rankings or other modes?

**Comment by dingyinghu** [comment] 2020-02-04 06:40
Thank you for your reply!
this picture show what system i use,and i use daily top in app
![Screenshot_2020-02-04-14-37-18-658_com android settings](https://user-images.githubusercontent.com/32993902/73720046-06827e00-475c-11ea-8eaa-0835d866d5fd.png)

**Comment by dingyinghu** [comment] 2020-02-04 06:56
And now,i find if i change ranking model, such as changing daily top to weekly top.The **first time** i click the name,it will respond to my click and pop up the call interface(still can't open app), after that,it will be no response until i changing ranking model again.

**Comment by yellowbluesky** [comment] 2020-02-04 08:09
Hi,

I have identified a critical error in my app preventing it from downloading images and storing their data properly. In the next hour or so I will push out an update that may fix your issue

**Comment by dingyinghu** [comment] 2020-02-04 08:10
Thanks a lot

**Comment by yellowbluesky** [comment] 2020-02-04 08:31
Hi there,

I mistakenly spoke earlier. I did identify a fault, but it is a minor potential one. I do not believe it to be the cause of your issues. I will continue investigating.

**Comment by yellowbluesky** [comment] 2020-02-05 23:15
PixivforMuzeiPlus adds a view INTENT to the Artwork builder:

```java
artwork = New Artwork.Builder()
    .viewIntent(new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.pixiv.net/member_illust.php?mode=medium&illust_id=" + info.getImg_id())))
```

https://github.com/moeoverflow/PixivForMuzeiPlus/blob/89c252c3622d6b8e611ca25267860d5f8e4455d8/app/src/main/java/moe/democyann/pixivformuzeiplus/util/PixivUser.java#L218

This is no longer supported with the latest version of Muzei, I cannot do something similar.

What I currently do is submit a a web URL to Muzei

https://github.com/yellowbluesky/PixivforMuzei3/blob/49e033b0b0f0b1ba7ba858092c481a74791d84c7/app/src/main/java/com/antony/muzei/pixiv/PixivArtWorker.java#L317

My app does not handle anything to do with opening the browser or app, that is all up to Muzei or your OS.

However, what I can do is add a custom command to open a intent to a browser or app, like what PixivforMuzeiPlus does. This is adding a bit of redundancy, but it is not a lot of work, and it will likely work for you.

**Comment by yellowbluesky** [comment] 2020-02-05 23:57
Work has been done in c4c19fef5d670de28a55c661f13746df7938eea0.

Will build and test once I get off work in a few hours

**Comment by dingyinghu** [comment] 2020-02-06 02:02
Thanks a lot！
I hope this patch will solve the problem. 
Anyway, thank you for your hard work.

**Comment by yellowbluesky** [comment] 2020-02-06 09:16
https://github.com/yellowbluesky/PixivforMuzei3/releases/tag/2.6.6

Hi, can you try this release, and let me know if it works? 

You may need to uninstall your current version of the app if it is installed Play Store to install the version downloaded from Github.

![Screenshot_20200206-201436](https://user-images.githubusercontent.com/11283778/73922593-87d53e80-491d-11ea-92f2-93e53c3d6c9e.jpg)

If it works, I will flesh out the feature, adding a chinese translation and such.

**Comment by dingyinghu** [comment] 2020-02-06 15:12
Thank you for your hard work! 
But I don't have a PC to compile the APK at present (including the next few days), so can you help me compile it?
I am sorry for the extra work.
Thanks again.

**Comment by yellowbluesky** [comment] 2020-02-06 20:25
Try the release link again, I've uploaded an apk there

I'm very very sorry, I forgot to upload an apk there when making the release

**Comment by dingyinghu** [comment] 2020-02-07 03:37
It work now!
But there are some unexpected situations. Now no matter I click the button or the title, it can call the app normally. I tried to download the old version of the app from the play store and found that it still can't call the app.
I don't understand how they influence each other or why it can call app by click the title now. Maybe it is a good change,i think.
This help me a lot.
Thanks again!

**Comment by yellowbluesky** [comment] 2020-02-07 03:48
Thanks for getting back with your feedback. 

Indeed, it is very strange that the two affect each other. I'll leave the command in as it's not in the way.

I'll close the issue when I upload this build to the Play Store, and I'll let you know then so you can install the version from there

**Comment by yellowbluesky** [comment] 2020-02-09 23:36
The latest version on the Play Store (2.7.1) includes this fix.

If you want to automatically get updates, uninstall the version you installed from here, and install it from the Play Store. Thanks

**Closed by yellowbluesky** 2020-02-09 23:36 UTC
Labels: question

**Comment by dingyinghu** [comment] 2020-02-10 01:54
Thank you!
