### ISSUE TITLE
Update mode: Recommended (Login required) without SFW doesn't do anything?

### ISSUE THREAD

**Issue by jasonkhanlar** [yellowbluesky/PixivforMuzei3#118] opened 2020-07-12 20:56 UTC
Update mode: Recommended (Login required)
+
Feed NSFW filter level: Slightly ecchi, Fairly ecchi, R18 (SFW is deselected)
doesn't do anything?

I just discovered and started using Muzei3 and Pixiv for Muzei3.
All the modes that don't require login work wonderfully, but I'm not sure about the ones that do require login.
Just a few days ago, I created a fresh new empty blank Pixiv account specifically for my Android phone and this app. I'm not sure if this may be related, cause or not.
I am logged in to the Pixiv account through Pixiv for Muzei3.

When I select Update mode: Recommended (Login required)
and also deselect SFW in the Feed NSFW filter level, leaving the rest checked
then after I exit from settings, I see the "New update mode, clearing image cache" tooltip appear and disappear
Even after waiting minutes, hours, and now days, nothing seems to happen. I checked in File Manager the directory where the picture files are stored, and nothing seems to be retrieved with the mode, even though I am logged in.

If I select the SFW Feed NSFW filter level option though, then I see content.

How come?

I am using an LG G4 phone with Android v6.0

**Comment by yellowbluesky** [comment] 2020-07-12 23:37
Thanks for your report. I've read and acknowledged your issue.

I'll get back to you in a few hours once I'm off work.

**Comment by jasonkhanlar** [comment] 2020-07-13 02:50
Q: Are you following at least one artist on Pixiv?

A: I didn't think I was. It was a fresh/blank/new account. I was going to say no, but I see https://www.pixiv.net/en/users/56459853/following shows 1 following, 0 followers: 

It appears I am following Pixiv Fanbox https://www.pixiv.net/en/users/11 by default. I don't remember selecting this.



Q: On the Pixiv website itself, are you able to view NSFW art when you are logged in?

A: Using the 12 examples mentioned in https://github.com/yellowbluesky/PixivforMuzei3/wiki/Explanation-of-NSFW-filtering-levels while logged in to the account, here is what I see:

1: I see it
2: I see it
3: I see it

4: It appears deleted, maybe update this with a new example
5: It appears deleted, maybe update this with a new example
6: I see it

7: I see it
8: I see it
9: I see it

10: i see message "You've chosen not to see R-18 works"
11: i see message "You've chosen not to see R-18 works"
12: i see message "You've chosen not to see R-18 works"

(for the last 3), I edited settings to enable both R-18 and R-18G and now

10: I see it
11: I see it
12: I see it

Q: Are you able to take a logcat of the app running? Or more invasively, you can share your Pixiv credentials with me, but I don't expect you to

A: Maybe I can try later, but I don't think it should be difficult to reproduce with a fresh new account. I literally just created an account for the sole purpose of using it with the app to check out the update modes that required logging in.

Also note:

After I changed setting on my Pixiv account to enable both R-18 and R-18G, I also changed Update mode in the app to Daily ranking and then back to Recommended (Login Required) to test and see if it works now, and it seems that it does! Note that the Feed NSFW filter level was still SFW (unchecked), Slightly ecchi (checked), Fairly ecchi (checked), R18 (checked). Those settings were not loading any images until I added R-18/R-18G. However, if, before the Pixiv account settings change, I also checked the SFW option, then it would work.

**Comment by yellowbluesky** [comment] 2020-07-13 03:09
Ok, thanks for your detailed response, and thanks for letting me know that some of the artworks have been deleted or moved.

I'll see if I can replicate your issues with a brand new and fresh account tonight. I don't think I need anything more from you at this moment.

**Comment by jasonkhanlar** [comment] 2020-07-13 05:24
Sure. Also I tinkering a little bit more and it seems still there is a similar/related issue.

This is AFTER I updated my Pixiv account settings so that nothing is censored. I now see all ratings, including R-18/R-18G.

For testing purposes, I'm switching from the Muvie 3 Featured Art source and then back to Pixiv for Muzei 3 source to make sure the image is changing (or not)

I deleted all the images in the cache:
/storage/emulated/0/Android/data/com.antony.muzei.pixiv/ is basically empty except for empty directory ./files/Pictures/

and in File Manager I renamed the download path:
/storage/emulated/0/Picdtures/PixivForMuzie3
to
/storage/emulated/0/Picdtures/PixivForMuzie3.backup

So, now with empty images, no cache, trying to download new images, I set the Pixiv for Muzei 3 setting to minimal one specific filter level at a time:

Update mode: Recommended (Login Required) -- I am logged in still
Feed NSFW filter level: Only R18 is selected, everything else is deselected

Nothing is downloaded at all after many minutes, and longer time. The wallpaper still shows from the other source (Featured art).

Deselecting "R18" and Selecting "Fairly ecchi":

This works! The wallpaper changed!  But I think that I had to change the source to Featured art and then back to Pixiv for Muzei 3 to trigger the new settings. Is it possible that when the Feed NSFW filter level setting changes value, that the new settings can trigger a "New Feed NSFW filter level, clearing image cache" tooltip?

So, I think there is something broken specifically with the R18 Feed NSFW filter level, that no images return from Pixiv API query

**Comment by yellowbluesky** [comment] 2020-07-13 06:19
Hi, I believe that Pixiv's Recommended feed will not show R18 pictures to you under any circumstances, so the "hanging" with only R18 selected is correct behaviour.

The error reporting is a bit opaque, I will implement a better indication to the user that their combination of source and NSFW filtering level does not work.

**Comment by yellowbluesky** [comment] 2020-07-13 10:56
Ok, I just took a look at the response JSON from the Recommended source. It looks like all artwork from this source is SFW, so if you deselect SFW from your filtering no artwork will match the criteria causing the app to fail.

This is not a bug, but I will make changes to my app to:

- Allow all artwork regardless of user choice

- Somehow communicate this to the user

I am not sure what happened when "Slightly Ecchi" downloaded an artwork for you. Nothing should have continued to happen until you select SFW.

All other sources allow arbitrary selection of NSFW filtering.

**Comment by jasonkhanlar** [comment] 2020-07-14 10:30
I now see the https://www.pixiv.net/ranking.php page and
https://www.pixiv.net/ranking.php?mode=daily
https://www.pixiv.net/ranking.php?mode=daily_r18

but I do not see anywhere in the code "daily_r18"

I am testing the Update mode: Daily ranking and comparing the SFW vs NSFW filter level. When I use NSFW filter, then I see a wallpaper that is from the SFW entries. Same for Weekly, and probably also the others too.

**Comment by yellowbluesky** [comment] 2020-07-14 11:36
My app doesn't have any of the R18 ranking update modes. It requires some configuration in how I send my requests that I have not yet determined.

For all the ranking modes, in order to filter for SFW vs NSFW, my app [checks for the"sexual" tag](https://github.com/yellowbluesky/PixivforMuzei3/blob/cbfd5cca71b460855b7b8c5f380db0683685e2f3/app/src/main/java/com/antony/muzei/pixiv/provider/PixivArtWorker.kt#L483) in the JSON response I receive.
There's no other information that my app can use.

Additionally, my handles albums, by only displaying the first picture (lazy I know). The NSFW tag may come from the following artwork in the album.

**Comment by yellowbluesky** [comment] 2020-08-03 11:17
Fixed in d35dc8b865a20efa6eb7ab30dd8ac76b34965d61

**Closed** 2020-10-14 08:29 UTC
Labels: bug
